### PR TITLE
Feature/config granularity

### PR DESCRIPTION
**Pull request by aidantwoods**
Adds some configuration options for fine tuning hsts, currently a WIP that can be improved upon.

### CODE REVIEW

**Comment by mikefrancis** [comment]
@aidantwoods Is this branch ready to go? It still has [WIP] in the title

**Comment by aidantwoods** [comment]
@mikefrancis not quite yet – I was planning on adding a few other config options for things such as CSP report only and strict mode.

**Comment by aidantwoods** [comment]
@mikefrancis I'm not sure what's going on with Travis, I've tried force pushing "new" commits (different hashes, same content) a couple times but looks like the build is having trouble starting.

**Comment by mikefrancis** [comment]
@aidantwoods Strange - can you try pushing again please? Have had a play around with some Travis settings.

**Comment by aidantwoods** [comment]
Looks like that got it

**Comment by mikefrancis** [comment]
You might need to rebase here - I have just merged some changes to the test (based on yours, so thank you!).

**Comment by aidantwoods** [comment]
> You might need to rebase here - I have just merged some changes to the test (based on yours, so thank you!).

Uhh, I can rebase, but the conflicts are very problematic ;p

Should I change the new `applySecureHeadersWithConfig` to support setting multiple keys for example? I need this to test strictmode with safemode.

**Comment by mikefrancis** [comment]
You can do, yes - I did that test too and got around it by passing the response to another response: https://github.com/mikefrancis/laravel-secureheaders/blob/master/tests/ApplySecureHeadersTest.php#L62

**Comment by aidantwoods** [comment]
I ended up rewriting that method and then cherry picking your changes on top since it made the conflicts a little easier to resolve (see: https://github.com/mikefrancis/laravel-secureheaders/compare/master...aidantwoods:test).

If you're happy with the final state there I can just force-push the diff to this PRs branch in a single commit.

**Comment by aidantwoods** [comment]
>  I did that test too and got around it by passing the response to another response: 

My only objection to that method is that it uses two instances of SecureHeaders and also the middleware one after the other – in theory this shouldn't make a difference for this case, but it becomes order dependent: i.e. you have to do safe mode last (if you only use one instance it doesn't matter).
Possible this would matter more in other cases too. I think it is a more accurate simulation to put all the config options into one instance (since this is how the middleware runs in normal use AFAIK).

**Comment by aidantwoods** [comment]
Also, before I forget to ask:

With the added options for HSTS, how would you prefer to proceed on the `enabled` option.
Should `enabled` be required for HSTS to go out, or should it be optional in the case that a max-age is given for example (i.e. more similar to the expectCT config layout)..

I.e. at present, HSTS will only go out if `isset(hsts.enabled)`, but should we change it so that it is `isset(hsts.enabled) || isset(hsts.maxAge)` ?

**Comment by aidantwoods** [comment]
> I can just force-push the diff to this PRs branch in a single commit.

Never-mind, I managed to make it though all the conflicts.

**Pull request merged**
